#!/usr/bin/env perl

use strict;
use warnings;

use lib ('lib', 'local/lib/perl5');

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('Xqursion');
